### ISSUE TITLE
Flickity carousel ends up with an arbitrary height until the viewport is resized, causing the content to be unreadable

### ISSUE THREAD

**Issue by jackbuehner** [troop-370/troop370#87]
The element with class `.flickity-viewport` ends up with something like `height: 120.722px` applied inline, overriding `height: 100%` applied in our css.

We need to investigate what is causing this issue. I have no idea the cause, but it is resulting in the cards to be cut off for first-time visitors.

@quintoncables Can you look into this?

**Comment by quintoncables** [comment]
Sure thing

**Comment by jackbuehner** [comment]
Any updates on this? @quintoncables

**Comment by quintoncables** [comment]
Not only is this happening with height, but also width in my case. Either the issue is also happening in`flickity-slider` or its just more specifically occurring there. Even when I set `flickity-viewport` to equal 100%, the cards are still horizontally clumped. Below is an example with the height at 100% 
![image](https://user-images.githubusercontent.com/46767928/68088219-bd542280-fe2a-11e9-9c68-65a326676ca6.png)

Maybe the margin is messed up? I also have 0 clue as to what is causing the issue but I hope this helped slightly.

**Comment by jackbuehner** [comment]
There's a similar issue at metafizzy/flickity#972

**Comment by quintoncables** [comment]
any update on this? Is flickity aware of it?
